#!/usr/bin/env bash
# scripts/backup/entrypoint.sh — image entrypoint. Two modes:
#
#   cron                   — default. Run busybox crond in foreground
#                            so docker can track liveness. Cron table
#                            at /etc/cron.d/planeai-backup invokes our
#                            scripts.
#   <name-of-script>.sh    — passthrough. Runs the named script once
#                            with the env that's already in scope.
#                            Useful for ad-hoc restore-tests:
#                              docker run ... entrypoint.sh restore_test.sh latest

set -Eeuo pipefail

cmd="${1:-cron}"

if [ "$cmd" = "cron" ]; then
  # busybox crond needs the file in /etc/crontabs/<user>, but we ship
  # ours in /etc/cron.d for compatibility with classic cron layouts.
  # Concatenate into /etc/crontabs/root so busybox picks it up.
  install -d /etc/crontabs
  # Strip lines that start with a username field (classic cron) — busybox
  # cron expects <m h d mo dow command> with NO user column.
  sed -E 's/^([0-9*\/, -]+) +[a-z]+ +/\1 /' /etc/cron.d/planeai-backup > /etc/crontabs/root
  chmod 0600 /etc/crontabs/root

  # Propagate the runtime env into a file cron jobs source. Cron jobs
  # otherwise start with the minimal cron environment and would miss
  # POSTGRES_*, BACKUP_S3_*, etc.
  install -d /opt/backup
  {
    echo "# auto-generated by entrypoint.sh — sourced by cron jobs"
    env | grep -E '^(POSTGRES_|AWS_|BACKUP_|TZ=|PATH=)' | sed 's/^/export /'
  } > /opt/backup/cron_env.sh
  chmod 0600 /opt/backup/cron_env.sh

  echo "[entrypoint] starting crond" >&2
  exec crond -f -l 8 -L /dev/stderr
fi

# Passthrough mode: run the named script.
if [ -x "/opt/backup/${cmd}" ]; then
  shift
  exec "/opt/backup/${cmd}" "$@"
fi

echo "[entrypoint] unknown command: ${cmd}" >&2
exit 64
