# Generated by Django 4.2.30 on 2026-05-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import pgvector.django.indexes
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProjectSettings',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_settings', serialize=False, to='db.project')),
                ('exclude_from_ai', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI project settings',
                'verbose_name_plural': 'AI project settings',
                'db_table': 'ai_project_settings',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAIConfig',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_config', serialize=False, to='db.workspace')),
                ('anthropic_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('openai_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('chat_model', models.CharField(default='claude-sonnet-4-6', max_length=60)),
                ('embed_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('monthly_token_budget', models.BigIntegerField(default=5000000)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace AI config',
                'verbose_name_plural': 'Workspace AI configs',
                'db_table': 'ai_workspace_config',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('intent_search', 'intent_search'), ('summarize', 'summarize'), ('bulk', 'bulk'), ('agent', 'agent'), ('embed', 'embed')], max_length=40)),
                ('model', models.CharField(max_length=60)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cache_read_tokens', models.IntegerField(default=0)),
                ('cache_creation_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage logs',
                'db_table': 'ai_usage_log',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('work_item', 'work_item'), ('comment', 'comment'), ('page', 'page')], max_length=20)),
                ('source_id', models.UUIDField()),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('token_count', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('content_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='db.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Document chunk',
                'verbose_name_plural': 'Document chunks',
                'db_table': 'ai_document_chunk',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ai_chunk_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['workspace', 'project'], name='ai_chunk_ws_prj_idx'), models.Index(fields=['source_type', 'source_id'], name='ai_chunk_src_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'chunk_index'), name='ai_chunk_unique_per_source'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['workspace', 'created_at'], name='ai_usage_ws_time_idx'),
        ),
    ]
