# Phase 7.1 — Multi-agent orchestrator schema.
#
# Four new tables (ProjectGoal, AgentAction, PredictedRisk,
# TeamVelocity) plus two new fields on WorkspaceAIConfig
# (agents_killed kill-switch, max_agent_actions_per_hour breaker cap).
#
# Generated by hand from ai.models because `manage.py makemigrations`
# in the prod image refuses to autogen against settings.AUTH_USER_MODEL
# when settings.production_ai is loaded.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0005_aiagentactionlog_undo"),
    ]

    operations = [
        # ---- WorkspaceAIConfig: kill-switch + breaker cap -----------
        migrations.AddField(
            model_name="workspaceaiconfig",
            name="agents_killed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspaceaiconfig",
            name="max_agent_actions_per_hour",
            field=models.IntegerField(default=60),
        ),
        # ---- ProjectGoal --------------------------------------------
        migrations.CreateModel(
            name="ProjectGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("deadline", models.DateField(blank=True, null=True)),
                ("constraints", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("planning", "planning"),
                            ("executing", "executing"),
                            ("at_risk", "at_risk"),
                            ("blocked", "blocked"),
                            ("done", "done"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("plan_preview", models.JSONField(blank=True, default=dict)),
                ("plan_issue_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_goals",
                        to="db.workspace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_goals",
                        to="db.project",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_goals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI project goal",
                "verbose_name_plural": "AI project goals",
                "db_table": "ai_project_goal",
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"], name="ai_goal_ws_status_idx"
                    ),
                    models.Index(
                        fields=["deadline"], name="ai_goal_deadline_idx"
                    ),
                ],
            },
        ),
        # ---- AgentAction -------------------------------------------
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_issue_id", models.UUIDField(blank=True, null=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("PLANNER", "PLANNER"),
                            ("MONITOR", "MONITOR"),
                            ("EXECUTOR", "EXECUTOR"),
                            ("ESCALATOR", "ESCALATOR"),
                            ("ANALYST", "ANALYST"),
                            ("COMMUNICATOR", "COMMUNICATOR"),
                            ("ORCHESTRATOR", "ORCHESTRATOR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_type", models.CharField(max_length=60)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("reasoning", models.TextField(blank=True, default="")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("NOTIFY", "NOTIFY"),
                            ("CONFIRM", "CONFIRM"),
                            ("ESCALATE", "ESCALATE"),
                        ],
                        default="AUTO",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "proposed"),
                            ("applied", "applied"),
                            ("rejected", "rejected"),
                            ("awaiting_user", "awaiting_user"),
                            ("failed", "failed"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_agent_actions",
                        to="db.workspace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_agent_actions",
                        to="db.project",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="ai.projectgoal",
                    ),
                ),
                (
                    "approved_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI agent action (orchestrator)",
                "verbose_name_plural": "AI agent actions (orchestrator)",
                "db_table": "ai_agent_action",
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"], name="ai_act_ws_time_idx"
                    ),
                    models.Index(
                        fields=["agent_type", "status"], name="ai_act_agent_status_idx"
                    ),
                    models.Index(
                        fields=["target_issue_id"], name="ai_act_issue_idx"
                    ),
                ],
            },
        ),
        # ---- PredictedRisk ------------------------------------------
        migrations.CreateModel(
            name="PredictedRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_id", models.UUIDField()),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("delay", "delay"),
                            ("blocker", "blocker"),
                            ("overload", "overload"),
                            ("dependency", "dependency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        default="medium",
                        max_length=12,
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                ("suggested_actions", models.JSONField(blank=True, default=list)),
                ("resolved", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_risks",
                        to="db.workspace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_risks",
                        to="db.project",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks",
                        to="ai.projectgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI predicted risk",
                "verbose_name_plural": "AI predicted risks",
                "db_table": "ai_predicted_risk",
                "indexes": [
                    models.Index(
                        fields=["workspace", "resolved", "impact"],
                        name="ai_risk_ws_open_idx",
                    ),
                    models.Index(
                        fields=["issue_id", "risk_type"], name="ai_risk_issue_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved", False)),
                        fields=("issue_id", "risk_type"),
                        name="ai_risk_unique_open",
                    ),
                ],
            },
        ),
        # ---- TeamVelocity -------------------------------------------
        migrations.CreateModel(
            name="TeamVelocity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_id", models.UUIDField()),
                ("task_type", models.CharField(default="uncategorised", max_length=60)),
                ("estimated_hours", models.FloatField(blank=True, null=True)),
                ("actual_hours", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_velocity",
                        to="db.workspace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_velocity",
                        to="db.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_velocity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI team velocity sample",
                "verbose_name_plural": "AI team velocity samples",
                "db_table": "ai_team_velocity",
                "indexes": [
                    models.Index(
                        fields=["workspace", "completed_at"], name="ai_vel_ws_time_idx"
                    ),
                    models.Index(
                        fields=["user", "task_type"], name="ai_vel_user_type_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issue_id",), name="ai_vel_unique_per_issue"
                    ),
                ],
            },
        ),
    ]
